### ISSUE TITLE
Some OpenStreetMap files cause AmbitBuildingGenerator and AmbitRoadGenerator to fail

### ISSUE THREAD

**Issue by kris-work** [aws-samples/aws-ambit-scenario-designer-ue4#9]
Some OSM files fail to cook properly when used with AmbitBuildingGenerator or AmbitRoadGenerator. The cook fails with an error message similar to the following:

```
Error
Invalid source /obj/test_fail/osm_import1/read_in_map_data
Error: Python error: Traceback (most recent call last):
File "<stdin>", line 328, in <module>
File "<stdin>", line 283, in parse
File "D:\Houdini19\python37\lib\xml\etree\ElementTree.py", line 1224, in iterator
data = source.read(16 * 1024)
File "D:/Houdini19/python37\lib\encodings\cp1252.py", line 23, in decode
return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 8596: character maps to <undefined>
```

This is a known issue that the AWS Ambit team is working to address. We don't yet know the conditions that cause the failure to occur, but we've noticed the issue happens frequently with OSM exports of the downtown Seattle area. A sample OSM file which causes these errors is attached.

We will update this issue as we learn more.

[map.osm.txt](https://github.com/aws-samples/aws-ambit-scenario-designer-ue4/files/7664028/map.osm.txt)

**Comment by brhook-aws** [comment]
This should now work properly on the latest Houdini build with the latest SideFX Labs installation, 19.0.498. For issues pertaining to this error, please upgrade to that version. 
If utilizing 18.5.x, please manually install the latest SideFX labs from the [GitHub repository](https://github.com/sideeffects/SideFXLabs ) until they backtrack it to that version of the software.
